use vaccine_reservation_system;

CREATE TABLE MEMBER(
	Mno	    	 INT		  NOT NULL  AUTO_INCREMENT,
    Name		 VARCHAR(10)  NOT NULL,
    Sex			 CHAR 		  NOT NULL,
    Phone		 VARCHAR(20),
    Email		 VARCHAR(30), 
    Age			 INT 		  NOT NULL,  
    City 		 VARCHAR(10)  NOT NULL,
    Addr_details VARCHAR(30),
    Id			 VARCHAR(20)  NOT NULL,
    Pwd			 VARCHAR(20)  NOT NULL,
    CONSTRAINT MEMBER_PK PRIMARY KEY(Mno),
    CONSTRAINT MEMBER_UQ UNIQUE(Id)
);

CREATE TABLE HOSPITAL(
	Hno   INT		   NOT NULL  AUTO_INCREMENT,
    Name  VARCHAR(20)  NOT NULL,
    Phone VARCHAR(20)  NOT NULL,
    City  VARCHAR(10)  NOT NULL,
    Gu    VARCHAR(10)  NOT NULL,
    Dong  VARCHAR(20)  NOT NULL,
    CONSTRAINT HOSPITAL_PK PRIMARY KEY(Hno)
);

CREATE TABLE DAYOFF(
	Hno INT     NOT NULL,
    Day CHAR(3) NOT NULL,
    CONSTRAINT DAYOFF_PK PRIMARY KEY(Hno, Day),
    CONSTRAINT DAYOFF_FK 
		FOREIGN KEY(Hno) REFERENCES HOSPITAL(Hno)
		ON DELETE CASCADE	ON UPDATE CASCADE
);

CREATE TABLE VACCINE(
	Vno  INT         NOT NULL  AUTO_INCREMENT,
    Name VARCHAR(20) NOT NULL,
    CONSTRAINT VACCINE_PK PRIMARY KEY(Vno)
);

CREATE TABLE POSSESSION(
	Hno 	INT NOT NULL,
    Vno 	INT NOT NULL,
    Remains INT NOT NULL,
    CONSTRAINT POSSESSION_PK PRIMARY KEY(Hno, Vno),
    CONSTRAINT POSSESSION_FK
		FOREIGN KEY(Hno) REFERENCES HOSPITAL(Hno)
		ON DELETE CASCADE	ON UPDATE CASCADE,
        FOREIGN KEY(Vno) REFERENCES VACCINE(Vno)
		ON DELETE CASCADE	ON UPDATE CASCADE
);

CREATE TABLE RESERVATION(
	Mno 		INT  NOT NULL,
	Hno 		INT  NOT NULL,
    Vno 		INT  NOT NULL,
    Date 		DATE NOT NULL,
    Time 		INT  NOT NULL,
    Inoculation INT  NOT NULL,
    CONSTRAINT RESERVATION_PK PRIMARY KEY(Mno, Hno, Vno, Inoculation),
    CONSTRAINT RESERVATION_FK
		FOREIGN KEY(Mno) REFERENCES MEMBER(Mno)
		ON DELETE CASCADE	ON UPDATE CASCADE,
		FOREIGN KEY(Hno) REFERENCES HOSPITAL(Hno)
		ON DELETE CASCADE	ON UPDATE CASCADE,
        FOREIGN KEY(Vno) REFERENCES VACCINE(Vno)
		ON DELETE CASCADE	ON UPDATE CASCADE
);
